### ISSUE TITLE
Background playback does not work.

### ISSUE THREAD

**Issue by lililu754** [TeamNewPipe/NewPipe-legacy#33]
Background playback does not work.
Newpipe legacy 0.19.5
I am in Android version 4.2.2 - 17

every time i try the app crashes

**Comment by drogga** [comment]
Even tho it shows a error toast - background and pop-up play work, so this was been fixed and can be closed.
@friendlyanon the upstream is on 0.20.5 many things are probably fixed _(haven't read the changeslog, nor the issues there lately)_, so would you Please update this one _(also pls try solving the issue from my LogCat that I provided separately if you can)_ ?
Thanks.
_I plan to delete this comment after some time !_

**Comment by drogga** [comment]
Even tho it shows an error toast message - background and pop-up play work !, so this issue has been fixed and can be closed\deleted now...
@friendlyanon the upstream has many things fixed since the last build here, which btw is super outdated compared to the main non-Legacy builds, so would you or someone else (whoever) Please finally update this ?, it's long overdue... _(also please check the "issue" with my LogCat that I provided separately, which is supposedly fixed...)_
Thanks in advance.

_BTW - I plan to delete this comment after some time !_
